/*
Spotify Web API with fixes and improvements from sonallux

Testing MarketsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package spotifyclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Barben360/spotify-playlist-filters/app/spotifyclient"
)

func Test_spotifyclient_MarketsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MarketsApiService GetAvailableMarkets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MarketsApi.GetAvailableMarkets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
